//
// Created by fotyev on 2017-03-01.
//

#ifndef ZENGINE_SDL_WORKAROUND_HPP
#define ZENGINE_SDL_WORKAROUND_HPP

#include <SDL_version.h>

#include <SDL_pixels.h>

#if !SDL_VERSION_ATLEAST(2,0,5)

#define SDL_PIXELFORMAT_RGB24 SDL_DEFINE_PIXELFORMAT(SDL_PIXELTYPE_ARRAYU8, SDL_ARRAYORDER_RGB, 0, 24, 3)

#if SDL_BYTEORDER == SDL_BIG_ENDIAN
#define SDL_PIXELFORMAT_RGBA32 SDL_PIXELFORMAT_RGBA8888
#else
#define SDL_PIXELFORMAT_RGBA32 SDL_PIXELFORMAT_ABGR8888
#endif

#endif

#endif //ZENGINE_SDL_WORKAROUND_HPP
